name: blinpy
channels:
- defaults
dependencies:
- _libgcc_mutex=0.1
- argon2-cffi=20.1.0
- async_generator=1.10
- attrs=20.3.0
- backcall=0.2.0
- blas=1.0
- bleach=3.3.0
- ca-certificates=2021.4.13
- certifi=2020.12.5
- cffi=1.14.5
- cycler=0.10.0
- dbus=1.13.18
- decorator=5.0.6
- defusedxml=0.7.1
- entrypoints=0.3
- expat=2.3.0
- fontconfig=2.13.1
- freetype=2.10.4
- glib=2.68.1
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- icu=58.2
- importlib-metadata=3.10.0
- importlib_metadata=3.10.0
- iniconfig=1.1.1
- intel-openmp=2021.2.0
- ipykernel=5.3.4
- ipython=7.22.0
- ipython_genutils=0.2.0
- ipywidgets=7.6.3
- jedi=0.17.2
- jinja2=2.11.3
- jpeg=9b
- jsonpickle=2.0.0
- jsonschema=3.2.0
- jupyter=1.0.0
- jupyter_client=6.1.12
- jupyter_console=6.4.0
- jupyter_core=4.7.1
- jupyterlab_pygments=0.1.2
- jupyterlab_widgets=1.0.0
- kiwisolver=1.3.1
- lcms2=2.12
- ld_impl_linux-64=2.33.1
- libffi=3.3
- libgcc-ng=9.1.0
- libgfortran-ng=7.3.0
- libpng=1.6.37
- libsodium=1.0.18
- libstdcxx-ng=9.1.0
- libtiff=4.1.0
- libuuid=1.0.3
- libxcb=1.14
- libxml2=2.9.10
- lz4-c=1.9.3
- markupsafe=1.1.1
- matplotlib=3.3.4
- matplotlib-base=3.3.4
- mistune=0.8.4
- mkl=2021.2.0
- mkl-service=2.3.0
- mkl_fft=1.3.0
- mkl_random=1.2.1
- more-itertools=8.7.0
- nbclient=0.5.3
- nbconvert=6.0.7
- nbformat=5.1.3
- ncurses=6.2
- nest-asyncio=1.5.1
- notebook=6.3.0
- numpy=1.20.1
- numpy-base=1.20.1
- olefile=0.46
- openssl=1.1.1k
- packaging=20.9
- pandas=1.2.4
- pandoc=2.12
- pandocfilters=1.4.3
- parso=0.7.0
- pcre=8.44
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=8.2.0
- pip=21.0.1
- pluggy=0.13.1
- prometheus_client=0.10.1
- prompt-toolkit=3.0.17
- prompt_toolkit=3.0.17
- ptyprocess=0.7.0
- py=1.10.0
- pycparser=2.20
- pygments=2.8.1
- pyparsing=2.4.7
- pyqt=5.9.2
- pyrsistent=0.17.3
- pytest=6.2.3
- python=3.9.4
- python-dateutil=2.8.1
- pytz=2021.1
- pyzmq=20.0.0
- qt=5.9.7
- qtconsole=5.0.3
- qtpy=1.9.0
- readline=8.1
- scipy=1.6.2
- send2trash=1.5.0
- setuptools=52.0.0
- sip=4.19.13
- six=1.15.0
- sqlite=3.35.4
- terminado=0.9.4
- testpath=0.4.4
- tk=8.6.10
- toml=0.10.2
- tornado=6.1
- traitlets=5.0.5
- tzdata=2020f
- wcwidth=0.2.5
- webencodings=0.5.1
- wheel=0.36.2
- widgetsnbextension=3.5.1
- xz=5.2.5
- zeromq=4.3.4
- zipp=3.4.1
- zlib=1.2.11
- zstd=1.4.9
